name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for npm) or Python (for pytest)
        uses: actions/setup-node@v3
        with:
          node-version: 18
        # OR for Python:
        # uses: actions/setup-python@v4
        # with:
        #   python-version: '3.10'

      - name: Install dependencies
        run: npm install
        # OR: run: pip install -r requirements.txt

      - name: Run tests
        run: npm test
        # OR: run: pytest
